
app:
  build: .
  # command: gunicorn --worker-class eventlet dev_server:app
  command: ls
  command: gunicorn --worker-class eventlet server:app --bind 0.0.0.0:8000
  ports:
    - 8000:8000
  links:
    - db
db:
  image: mongo:latest
  hostname: mongodb
  environment:
    - MONGO_INITDB_DATABASE=tac_world
  ports:
    - 27017:27017
redis:
  image: redis:latest
  hostname: redis
  ports:
    - 6379:6379
